package projectUAS;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
/**
 *
 * @author ALTAIR
 */
public class formTiket extends javax.swing.JFrame {

    /**
     * Creates new form formTiket
     */
    public formTiket() {
        initComponents();
    }
    
    public void table() {
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("Nama");
        tbl.addColumn("Film");
        tbl.addColumn("Waktu");
        tbl.addColumn("Jml_Tiket");
        tbl.addColumn("Bangku");
        tbl.addColumn("Total");
        table.setModel(tbl);
        try{
            connDBMS Koneksi = new connDBMS();
            Statement stat = Koneksi.getConnection().createStatement();
            String sql = "SELECT * FROM pegawai6642";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("Nama"),
                    rs.getString("Film"),
                    rs.getString("Waktu"),
                    rs.getString("Jml_Tiket"),
                    rs.getString("Bangku"),
                    rs.getString("Total")
                });
            table.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Attribut salah");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPemesan = new javax.swing.JTextField();
        JudulFilm = new javax.swing.JLabel();
        txtFilm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        cbJam = new javax.swing.JComboBox<>();
        JmlTiket = new javax.swing.JLabel();
        cbTiket = new javax.swing.JComboBox<>();
        Bangku = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        A1 = new javax.swing.JCheckBox();
        A2 = new javax.swing.JCheckBox();
        A3 = new javax.swing.JCheckBox();
        A4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        B1 = new javax.swing.JCheckBox();
        B2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        B3 = new javax.swing.JCheckBox();
        B4 = new javax.swing.JCheckBox();
        C4 = new javax.swing.JCheckBox();
        C1 = new javax.swing.JCheckBox();
        C2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        C3 = new javax.swing.JCheckBox();
        D4 = new javax.swing.JCheckBox();
        D1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        D3 = new javax.swing.JCheckBox();
        D2 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTagihan = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 22)); // NOI18N
        jLabel1.setText("FORM PEMESANAN");

        jLabel2.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 22)); // NOI18N
        jLabel2.setText("TIKET BIOSKOP");

        jLabel3.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        jLabel3.setText("Nama Pemesan");

        txtPemesan.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N

        JudulFilm.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        JudulFilm.setText("Judul Film");

        txtFilm.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Swis721 WGL4 BT", 2, 12)); // NOI18N
        jLabel5.setText("print");

        Waktu.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        Waktu.setText("Jam Tayang");

        cbJam.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        cbJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH JAM TAYANG--", "Pagi", "Siang", "Sore", "Malam" }));

        JmlTiket.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        JmlTiket.setText("Jumlah Tiket");

        cbTiket.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        cbTiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Bangku.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        Bangku.setText("Tempat Duduk");

        txtSeat.setFont(new java.awt.Font("Swis721 WGL4 BT", 2, 14)); // NOI18N

        A1.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        A1.setText("A1");

        A2.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        A2.setText("A2");

        A3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        A3.setText("A3");

        A4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        A4.setText("A4");

        jLabel9.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        jLabel9.setText("A");

        B1.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        B1.setText("B1");

        B2.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        B2.setText("B2");

        jLabel10.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        jLabel10.setText("B");

        B3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        B3.setText("B3");

        B4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        B4.setText("B4");

        C4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        C4.setText("C4");

        C1.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        C1.setText("C1");

        C2.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        C2.setText("C2");

        jLabel11.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        jLabel11.setText("C");

        C3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        C3.setText("C3");

        D4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        D4.setText("D4");

        D1.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        D1.setText("D1");

        jLabel12.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        jLabel12.setText("D");

        D3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        D3.setText("D3");

        D2.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        D2.setText("D2");

        jLabel13.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 14)); // NOI18N
        jLabel13.setText("Total Tagihan");

        jLabel14.setFont(new java.awt.Font("Swis721 WGL4 BT", 2, 14)); // NOI18N
        jLabel14.setText("Rp.");

        txtTagihan.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 22)); // NOI18N
        txtTagihan.setText("0");

        cbFilm.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        cbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH JUDUL FILM--", "TITANIC (1997)", "Laskar Pelangi (2008)", "Habibie & Ainun (2012)", "Fast & Furious 7 (2015)", "AVENGERS: Infinity War (2018)", "AVENGERS: ENDGAME (2019)" }));

        table.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnSubmit.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Waktu)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JudulFilm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPemesan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(JmlTiket)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTiket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbJam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bangku)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSeat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(A1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(A2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(A3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(A4)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B2)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(C1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C2)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(D1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D2)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTagihan))
                                .addComponent(jLabel13)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bangku)
                        .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A1)
                        .addComponent(A2)
                        .addComponent(A3)
                        .addComponent(A4)
                        .addComponent(jLabel9))
                    .addComponent(txtPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JudulFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Waktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JmlTiket)
                            .addComponent(cbTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B1)
                            .addComponent(B2)
                            .addComponent(jLabel10)
                            .addComponent(B3)
                            .addComponent(B4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C1)
                            .addComponent(C2)
                            .addComponent(jLabel11)
                            .addComponent(C3)
                            .addComponent(C4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D1)
                            .addComponent(jLabel12)
                            .addComponent(D3)
                            .addComponent(D4)
                            .addComponent(D2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtTagihan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int JudulFilm = cbFilm.getSelectedIndex();
        int Waktu = cbJam.getSelectedIndex();
        int JmlTiket = cbTiket.getSelectedIndex();
        int SatuanHargaTiket = 0;
        int Total = 0;
        
        if(Waktu == 0){
            JOptionPane.showMessageDialog(null, "Maaf, anda belum memilih jam tayang..");
        }
        else if (JudulFilm == 0){
            JOptionPane.showMessageDialog(null, "Anda belum memilih judul film..");
        }
        else {
            switch(JudulFilm){
                case 1: SatuanHargaTiket = 40000;break;
                case 2: SatuanHargaTiket = 40000;break;
                case 3: SatuanHargaTiket = 40000;break;
                case 4: SatuanHargaTiket = 40000;break;
                case 5: SatuanHargaTiket = 40000;break;
                case 6: SatuanHargaTiket = 40000;break;
            }
            Total = SatuanHargaTiket * JmlTiket;
            txtTagihan.setText(String.valueOf(Total));
        }
        
        String Bangku;
        Bangku = "";
        if(A1.isSelected()){
            Bangku += A1.getText() + ", ";
        }
        if(A2.isSelected()){
            Bangku += A2.getText() + ", ";
        }
        if(A3.isSelected()){
            Bangku += A3.getText() + ", ";
        }
        if(A4.isSelected()){
            Bangku += A4.getText() + ", ";
        }
        if(B1.isSelected()){
            Bangku += B1.getText() + ", ";
        }
        if(B2.isSelected()){
            Bangku += B2.getText() + ", ";
        }
        if(B3.isSelected()){
            Bangku += B3.getText() + ", ";
        }
        if(B4.isSelected()){
            Bangku += B4.getText() + ", ";
        }
        if(C1.isSelected()){
            Bangku += C1.getText() + ", ";
        }
        if(C2.isSelected()){
            Bangku += C2.getText() + ", ";
        }
        if(C3.isSelected()){
            Bangku += C3.getText() + ", ";
        }
        if(C4.isSelected()){
            Bangku += C4.getText() + ", ";
        }
        if(D1.isSelected()){
            Bangku += D1.getText() + ", ";
        }
        if(D2.isSelected()){
            Bangku += D2.getText() + ", ";
        }
        if(D3.isSelected()){
            Bangku += D3.getText() + ", ";
        }
        if(D4.isSelected()){
            Bangku += D4.getText() + ", ";
        }
        
        else {
            Bangku = Bangku.substring(0, Bangku.length()-2) + ", ";
            txtSeat.setText(Bangku);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int stt = JOptionPane.showConfirmDialog(this, "Yakin Dihapus ?");
        System.out.print(stt);
        if(stt == 0){
            String Nama = txtPemesan.getText();
            try{
                connDBMS Koneksi = new connDBMS();
                Connection con = Koneksi.getConnection();
                Statement stat = con.createStatement();
                String strsql = ("delete from tbTiket where Nama='"+Nama+"';");
                int stsproses=stat.executeUpdate(strsql);
                JOptionPane.showMessageDialog(this, "Data Terhapus");
                con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                System.err.println("Kesalahan perintah SL : "+e.getMessage());
            }
            table();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Keluar", "Verifikasi", JOptionPane.OK_OPTION);
        
        if (pilih == JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String sql;
        ResultSet res;
        
        String Nama = txtPemesan.getText();
        int JudulFilm = cbFilm.getSelectedIndex();
        String JudulFilm2 = txtFilm.getText();
        int Waktu = cbJam.getSelectedIndex();
        int JumlahTiket = cbTiket.getSelectedIndex();
        String Bangku = txtSeat.getText();
        int Total = txtTagihan.getComponentCount();
        
        Bangku = "";
        if(A1.isSelected()){
            Bangku += A1.getText() + ", ";
        }
        if(A2.isSelected()){
            Bangku += A2.getText() + ", ";
        }
        if(A3.isSelected()){
            Bangku += A3.getText() + ", ";
        }
        if(A4.isSelected()){
            Bangku += A4.getText() + ", ";
        }
        if(B1.isSelected()){
            Bangku += B1.getText() + ", ";
        }
        if(B2.isSelected()){
            Bangku += B2.getText() + ", ";
        }
        if(B3.isSelected()){
            Bangku += B3.getText() + ", ";
        }
        if(B4.isSelected()){
            Bangku += B4.getText() + ", ";
        }
        if(C1.isSelected()){
            Bangku += C1.getText() + ", ";
        }
        if(C2.isSelected()){
            Bangku += C2.getText() + ", ";
        }
        if(C3.isSelected()){
            Bangku += C3.getText() + ", ";
        }
        if(C4.isSelected()){
            Bangku += C4.getText() + ", ";
        }
        if(D1.isSelected()){
            Bangku += D1.getText() + ", ";
        }
        if(D2.isSelected()){
            Bangku += D2.getText() + ", ";
        }
        if(D3.isSelected()){
            Bangku += D3.getText() + ", ";
        }
        if(D4.isSelected()){
            Bangku += D4.getText() + ", ";
        }
        else {
            Bangku = Bangku.substring(0, Bangku.length()-2) + ", ";
            txtSeat.setText(Bangku);
        }
        
        int SatuanHargaTiket = 0;
        
        if (JudulFilm == 0){
            JOptionPane.showMessageDialog(null, "Judul film belum dipilih!");
        }
        else if(JudulFilm == 1){
            JudulFilm2 = ("TITANIC (1997)");
            SatuanHargaTiket = 40000;
        }
        else if(JudulFilm == 2){
            JudulFilm2 = "Laskar Pelangi (2008)";
            SatuanHargaTiket = 40000;
        }
        else if(JudulFilm == 3){
            JudulFilm2 = "Habibie & Ainun (2012)";
            SatuanHargaTiket = 40000;
        }
        else if(JudulFilm == 4){
            JudulFilm2 = "Fast & Furious 7 (2015)";
            SatuanHargaTiket = 40000;
        }
        else if(JudulFilm == 5){
            JudulFilm2 = "AVENGERS: Infinity War (2018)";
            SatuanHargaTiket = 40000;
        }
        else if(JudulFilm == 6){
            JudulFilm2 = "AVENGERS: ENDGAME (2019)";
            SatuanHargaTiket = 40000;
        }
        Total = SatuanHargaTiket * JumlahTiket;
        
        try {
            connDBMS Koneksi = new connDBMS();
            Connection conn = Koneksi.getConnection();
            Statement stat = conn.createStatement();
            
            
            sql = "SELECT * FROM tbTiket WHERE Nama ='"+Nama+"'";
            res = stat.executeQuery(sql);
            
            if(res.next()){
                JOptionPane.showMessageDialog(this, "Nama sudah ada!");
                return;
            }
            
            sql = String.format("INSERT INTO tbTiket values('%s','%s','%s','%s','%s','%s')",Nama, JudulFilm2,Waktu, JumlahTiket, Bangku, Total);
            int res_update = stat.executeUpdate(sql);
            
            if(res_update == 1){
                JOptionPane.showMessageDialog(this, "Sukses ditambahkan!");
                table();
                conn.close();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Penambahan Gagal");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1;
    private javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox A3;
    private javax.swing.JCheckBox A4;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox B3;
    private javax.swing.JCheckBox B4;
    private javax.swing.JLabel Bangku;
    private javax.swing.JCheckBox C1;
    private javax.swing.JCheckBox C2;
    private javax.swing.JCheckBox C3;
    private javax.swing.JCheckBox C4;
    private javax.swing.JCheckBox D1;
    private javax.swing.JCheckBox D2;
    private javax.swing.JCheckBox D3;
    private javax.swing.JCheckBox D4;
    private javax.swing.JLabel JmlTiket;
    private javax.swing.JLabel JudulFilm;
    private javax.swing.JLabel Waktu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbJam;
    private javax.swing.JComboBox<String> cbTiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtFilm;
    private javax.swing.JTextField txtPemesan;
    private javax.swing.JTextField txtSeat;
    private javax.swing.JLabel txtTagihan;
    // End of variables declaration//GEN-END:variables
}